#ifdef WIN32
"[Surface-Meta]\n"
"Name=Surface registry\n"
"Author=Margarit Alexandru-Daniel\n"

"[Surface]\n"
"SurfaceColor=0x0\n"
"AutoSize=1\n"
"Updatefrequency=-1\n"

"[Arrow]\n"
"Object=String\n"
"Text=\u25b2\n"
"W=20\n"
"H=20\n"
"Y=-4\n"
"X=$surfaceW$/2-10\n"
"Volatile=1\n"
"FontColor=0;0;0;128\n"

"[Background]\n"
"Volatile=1\n"
"Object=Image\n"
"BackColor=0;0;0;128\n"
"W=max([Title:X]+[Title:W],[Text:X]+[Text:W])+5\n"
"H=max([Title:Y]+[Title:H],[Text:Y]+[Text:H])-5\n"
"Y=-4R\n"
"UpdateAction=Update(Arrow)\n"

"[Title]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Title$\n"
"Y=5r\n"
"FontShadow=1\n"
"X=5\n"
"UpdateAction=Update(Background);ForceDraw()\n"
"[Text]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Text$\n"
"FontShadow=1\n"
"Y=5R\n"
"X=5\n"
"FontSize=10\n"
"FontName=Segoe UI\n"
"UpdateAction=Update(Background);ForceDraw()\n"
#elif __linux__
"[Surface-Meta]\n"
"Name=Surface registry\n"
"Author=Margarit Alexandru-Daniel\n"

"[Surface]\n"
"SurfaceColor=0x0\n"
"AutoSize=1\n"
"Updatefrequency=16\n"

"[Arrow]\n"
"Object=String\n"
"Text=\u25b2\n"
"W=20\n"
"H=20\n"
"Y=-4\n"
"X=$SurfaceW$/2-10\n"
"Volatile=1\n"
"FontColor=0;0;0;128\n"
"FontName=DejaVu Sans\n"

"[Background]\n"
"Volatile=1\n"
"Object=Image\n"
"BackColor=0;0;0;128\n"
"W=max([Title:X]+[Title:W],[Text:X]+[Text:W])+5\n"
"H=max([Title:Y]+[Title:H],[Text:Y]+[Text:H])-5\n"
"Y=-1R\n"
"UpdateAction=Update(Arrow)\n"

"[Title]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Title$\n"
"Y=5r\n"
"FontShadow=1\n"
"X=5\n"
"UpdateAction=Update(Background);ForceDraw()\n"
"FontName=DejaVu Sans\n"

"[Text]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Text$\n"
"FontShadow=1\n"
"Y=5R\n"
"X=5\n"
"FontSize=10\n"
"FontName=DejaVu Sans\n"
"UpdateAction=Update(Background);ForceDraw()\n"
#endif
