"[Surface]\n"
"UpdateFrequency=-1\n"
"AutoSize=1\n"
"\n"
"[Background]\n"
"Volatile=1\n"
"Object=Image\n"
"W=10+max([Title:W],[Text:W])\n"
"H=5+max([Text:Y]+[Text:H],[Title:Y]+[Title:H])\n"
"\n"
"[Title]\n"
"Volatile=1\n"
"Object = String\n"
"X = 5\n"
"Y = 5\n"
"FontName = Segoe UI\n"
"StringAlign = Center\n"
"FontShadow = 1\n"
"FontSize=12\n"
"\n"
"[Text]\n"
"Volatile=1\n"
"Object = String\n"
"X = 5\n"
"Y =[Title:Y]+[Title:H]+5\n"
"FontName = Segoe UI\n"
"FontSize = 10\n"
"FontShadow = 1\n"



