#ifdef WIN32
"[Surface-Meta]\n"
"Name=Surface registry\n"
"Author=Margarit Alexandru-Daniel\n"

"[Surface]\n"
"SurfaceColor=0x0\n"
"AutoSize=1\n"
"Updatefrequency=-1\n"

"[Arrow]\n"
"Object=String\n"
"Text=\u25b2\n"
"W=20\n"
"H=20\n"
"Y=-4\n"
"X=$surfaceW$/2-10\n"
"Volatile=1\n"
"FontColor=0;0;0;128\n"

"[Background]\n"
"Volatile=1\n"
"Object=Image\n"
"BackColor=0;0;0;128\n"
"W=max([Title:X]+[Title:W],[Text:X]+[Text:W])+5\n"
"H=max([Title:Y]+[Title:H],[Text:Y]+[Text:H])-5\n"
"Y=-4R\n"
"UpdateAction=Update(Arrow)\n"

"[Title]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Title$\n"
"Y=5r\n"
"FontShadow=1\n"
"X=5\n"
"UpdateAction=Update(Background);ForceDraw()\n"
"[Text]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Text$\n"
"FontShadow=1\n"
"Y=5R\n"
"X=5\n"
"FontSize=10\n"
"FontName=Segoe UI\n"
"UpdateAction=Update(Background);ForceDraw()\n"
#elif __linux__
"[Surface-Meta]\n"
"Name=Surface registry\n"
"Author=Margarit Alexandru-Daniel\n"

"[Surface]\n"
"SurfaceColor=0x0\n"
"AutoSize=1\n"
"Updatefrequency=16\n"

"[Arrow]\n"
"Object=String\n"
"Text=\u25b2\n"
"W=20\n"
"H=20\n"
"Y=-4\n"
"X=$SurfaceW$/2-10\n"
"Volatile=1\n"
"FontColor=0;0;0;128\n"
"FontName=DejaVu Sans\n"

"[Background]\n"
"Volatile=1\n"
"Object=Image\n"
"BackColor=0;0;0;128\n"
"W=max([Title:X]+[Title:W],[Text:X]+[Text:W])+5\n"
"H=max([Title:Y]+[Title:H],[Text:Y]+[Text:H])-5\n"
"Y=-1R\n"
"UpdateAction=Update(Arrow)\n"

"[Title]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Title$\n"
"Y=5r\n"
"FontShadow=1\n"
"X=5\n"
"UpdateAction=Update(Background);ForceDraw()\n"
"FontName=DejaVu Sans\n"

"[Text]\n"
"Volatile=1\n"
"Object=String\n"
"Text=$Text$\n"
"FontShadow=1\n"
"Y=5R\n"
"X=5\n"
"FontSize=10\n"
"FontName=DejaVu Sans\n"
"UpdateAction=Update(Background);ForceDraw()\n"
#endif
#if 1
"[Surface-Meta]\n"
"Name=Relu\\'s launcher\n"
"Author=Margarit Alexandru-Daniel\n"
"\n"
"[Surface]\n"
"UpdateFrequency=1000\n"
"SurfaceColor=0;0;0;0\n"
"AutoSize=1\n"
";----------------Sources---------------\n"
"[Surface-Variables]\n"
";-------Right ttip------\n"
";P1X=20\n"
";P1Y=100\n"
";P2X=0\n"
";P2Y=110\n"
";P3X=20\n"
";P3Y=120\n"
";----------Bottom------\n"
"\n"
"\n"
"RX = 0\n"
"RY = 8\n"
"TX = 100\n"
"TY = 0\n"
"\n"
"P1X = 0\n"
"P1Y = 0\n"
"P2X = 8.083\n"
"P2Y = 8.083\n"
"P3X = -8.083\n"
"P3Y = 8.083\n"
"Angle = 0\n"
"\n"
"[C]\n"
"Source=Calculator\n"
"Function=[C]+1\n"
"Volatile=1\n"
"\n"
"[Frame]\n"
"Volatile=1\n"
"Object=Vector\n"
"Path=Rect($RX$,$RY$,200,100);Stroke(0;255;0;255);\n"
"Path1=PathSet($P1X$,$P1Y$,1,Arrow);Rotate($Angle$);Offset([Frame:W]/2,$TY$);\n"
"Arrow=LineTo($P2X$,$P2Y$);LineTo($P3X$,$P3Y$)\n"
"Path2=Join(Path);Union(Path1);Fill(255;0;0;200);\n"
"BackColor=0;255;0;0\n"
"\n"
"[Title]\n"
"Object = String\n"
"Text = Tooltip title\n"
"X = $RX$ + 5\n"
"Y = $RY$ + 5\n"
"FontName = Segoe UI\n"
"StringAlign = Center\n"
"FontShadow = 1\n"
"W=[Frame:W] - $RX$ - 8\n"
"\n"
"\n"
"[Content]\n"
"Object = String\n"
"Source=C\n"
"Text = This is just an example text to show how the content is displayed in the tooltip %0\n"
"X = $RX$ + 5\n"
"Y = 5R\n"
"FontName = Segoe UI\n"
"FontSize = 10\n"
"FontShadow = 1\n"
"W=[Frame:W] - $RX$ - 8"
#endif
