#pragma once

typedef struct _xpander_request
{
    void* requestor;
    unsigned char req_type;
    unsigned char* os;
    unsigned char* es;
} xpander_request;

#define XPANDER_REQUESTOR_SURFACE 0x4
#define XPANDER_REQUESTOR_OBJECT 0x8
#define XPANDER_REQUESTOR_SOURCE 0x10
#define XPANDER_VARIABLES 0x1
#define XPANDER_SECTIONS 0x2
#define XPANDER_CONFIG   0x20

#define XPANDER_OBJECT XPANDER_REQUESTOR_OBJECT | XPANDER_SECTIONS | XPANDER_VARIABLES
#define XPANDER_SOURCE XPANDER_REQUESTOR_SOURCE | XPANDER_SECTIONS | XPANDER_VARIABLES
#define XPANDER_SURFACE XPANDER_REQUESTOR_SURFACE | XPANDER_SECTIONS | XPANDER_VARIABLES
#define XPANDER_SURFACE_CONFIG XPANDER_REQUESTOR_SURFACE | XPANDER_SECTIONS | XPANDER_VARIABLES | XPANDER_CONFIG
int xpander(xpander_request* xr);
